### ISSUE TITLE
build fails on windows10

### ISSUE THREAD

**Issue by fischeru** [ocampor/libsvm#2]
python 3.6.4
windows10 64 bit

Hi, I am trying to install libsvm on Windows using pip. I made sure to run the command as Administrator. I get the following error dump:

C:\WINDOWS\system32>pip install libsvm
Collecting libsvm
  Using cached https://files.pythonhosted.org/packages/ff/01/5506c690789f1d76105815d826f213ce724960851be45799d7023ed1aee7/libsvm-3.23.0.tar.gz
Building wheels for collected packages: libsvm
  Building wheel for libsvm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\fischeru\appdata\local\programs\python\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fischeru\\AppData\\Local\\Temp\\pip-install-l2fy__yl\\libsvm\\setup.py'"'"'; __file__='"'"'C:\\Users\\fischeru\\AppData\\Local\\Temp\\pip-install-l2fy__yl\\libsvm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\fischeru\AppData\Local\Temp\pip-wheel-xw6smf_n' --python-tag cp36
       cwd: C:\Users\fischeru\AppData\Local\Temp\pip-install-l2fy__yl\libsvm\
  Complete output (79 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\libsvm
  copying libsvm\commonutil.py -> build\lib.win-amd64-3.6\libsvm
  copying libsvm\svm.py -> build\lib.win-amd64-3.6\libsvm
  copying libsvm\svmutil.py -> build\lib.win-amd64-3.6\libsvm
  copying libsvm\__init__.py -> build\lib.win-amd64-3.6\libsvm
  running egg_info
  creating libsvm.egg-info
  writing libsvm.egg-info\PKG-INFO
  writing dependency_links to libsvm.egg-info\dependency_links.txt
  writing requirements to libsvm.egg-info\requires.txt
  writing top-level names to libsvm.egg-info\top_level.txt
  writing manifest file 'libsvm.egg-info\SOURCES.txt'
  reading manifest file 'libsvm.egg-info\SOURCES.txt'
  writing manifest file 'libsvm.egg-info\SOURCES.txt'
  running build_ext
  building 'libsvm' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\src
  creating build\temp.win-amd64-3.6\Release\src\libsvm
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\fischeru\appdata\local\programs\python\python36\include -Ic:\users\fischeru\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /EHsc /Tpsrc/libsvm/svm.cpp /Fobuild\temp.win-amd64-3.6\Release\src/libsvm/svm.obj
  svm.cpp
  src/libsvm/svm.cpp(53): warning C4996: 'vsprintf': This function or variable may be unsafe. Consider using vsprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  
*** lots of similar warnings ***

  C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt\string.h(439): note: Siehe Deklaration von "strtok"
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\fischeru\appdata\local\programs\python\python36\libs /LIBPATH:c:\users\fischeru\appdata\local\programs\python\python36\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64" /EXPORT:PyInit_libsvm build\temp.win-amd64-3.6\Release\src/libsvm/svm.obj /OUT:build\lib.win-amd64-3.6\libsvm.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\src/libsvm\libsvm.cp36-win_amd64.lib
  LINK : error LNK2001: Nicht aufgelöstes externes Symbol "PyInit_libsvm".
  build\temp.win-amd64-3.6\Release\src/libsvm\libsvm.cp36-win_amd64.lib : fatal error LNK1120: 1 nicht aufgelöste Externe
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120
  ----------------------------------------
  ERROR: Failed building wheel for libsvm
  Running setup.py clean for libsvm
Failed to build libsvm
 
Not sure why the linker is involved, the error is the german Version of 'unresolved external symbol'. I thought this is supposed to be pre-built. Any input on what is going on would be much appreciated.

**Comment by ocampor** [comment]
Thanks for reporting this. Actually, I haven’t test it on Windows. Only Unix distributions. Good news is that it is in my backlog. I will take a look and try to help you.

**Comment by fischeru** [comment]
thanks a lot in advance. btw: sorry for the strange formatting. I don't know why it ended up this way.

**Comment by ocampor** [comment]
@fischeru I included the pre-built libsvm.dll to the setup. I hope this fixes the problem.

**Comment by fischeru** [comment]
tested it and it works for me. thank you.
