### ISSUE TITLE
UnicodeDecodeError is raised when parse README.rst

### ISSUE THREAD

**Issue by zkonge** [ocampor/libsvm#5]
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zkong\AppData\Local\Temp\pip-install-3ksrxrho\libsvm\setup.py", line 18, in <module>
        LONG_DESCRIPTION = readme.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 3028: illegal multibyte sequence
```
Python text encoding depends on system. The Windows that use Chinese as system language uses cp936(GBK) encoding as the default text encoding, it can't parse unicode.

There are two solutions:
1. Replace `open(path)` with `open(path, encoding='UTF-8')`
https://github.com/ocampor/libsvm/blob/99f923e9602fab829704f4fa19780774065706c9/setup.py#L17

2. Replace ``` ``AS IS’’``` with `"AS IS"`
https://github.com/ocampor/libsvm/blob/99f923e9602fab829704f4fa19780774065706c9/README.rst#L111

**Comment by ocampor** [comment]
Thanks! I will fix and deploy the changes.

**Comment by ocampor** [comment]
The bug is fixed and deployed. You can check the commit a9770761bc11d6eb809ec1adf9def1ee71d8db34 for more details.
